name: update podman version

on:
  # schedule:
  #   - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch:
  push:
jobs:
  update-podman:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Get current podman version
        id: get_current_version
        run: |
          CURRENT_VERSION=$(jq -r '.version' extensions/podman/packages/extension/src/podman5.json)
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Fetch latest Podman release
        id: fetch_latest_podman_release
        run: |
          LATEST_PODMAN_RELEASE=$(curl -s https://api.github.com/repos/containers/podman/releases/latest)
          LATEST_VERSION=$(echo "$LATEST_PODMAN_RELEASE" | grep '"tag_name":' | awk -F'"' '{print $4}')
          ASSETS=$(echo "$LATEST_PODMAN_RELEASE" | grep '"name":' | awk -F '"' '{print $4}' | tr '\n' ' ')
          echo $LATEST_VERSION
          echo $ASSETS
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
          echo "$ASSETS" > assets.txt

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Compare version numbers using semver
        id: compare_varsion_numbers
        run: |
          echo "Current version: $CURRENT_VERSION"
          echo "Latest version: $LATEST_VERSION"
          pnpm add semver
          node -e "
            const semver = require('semver');
            const currentVersion = process.env.CURRENT_VERSION;
            const latestVersion = process.env.LATEST_VERSION;
            if(semver.gt(latestVersion,currentVersion)) {
              console.log('New version available:', latestVersion);
              console.log('::set-env name=NEW_VERSION::' + latestVersion);
            } else {
              console.log('No new version available.');
              process.exit(0);
            }
          "

      - name: Check for required assets in Podman release
        id: check_assets
        run: |
          REQUIRED_ASSETS=("podman-installer-windows-amd64.exe" "podman-installer-windows-arm64.exe" "podman-installer-macos-amd64.pkg" "podman-installer-macos-arm64.pkg" "podman-installer-macos-universal.pkg")
          MISSING_ASSETS=()
          for ASSET in "${REQUIRED_ASSETS[@]}"; do
            if ! grep -q "$ASSET" assets.txt; then
              MISSING_ASSETS+=("$ASSET")
            fi
          done
          if [ ${#MISSING_ASSETS[@} -ne 0]; then
            echo "Missing assets: ${MISSING_ASSETS[*]}"
            exit 1
          fi
