name: update podman version

on:
  # schedule:
  #   - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch:
  push:
jobs:
  update-podman:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Get current podman version
        id: get_current_version
        run: |
          CURRENT_VERSION=$(jq -r '.version' extensions/podman/packages/extension/src/podman5.json)
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_OUTPUT

      - name: Fetch latest Podman release
        id: fetch_latest_podman_release
        run: |
          LATEST_PODMAN_RELEASE=$(curl -s https://api.github.com/repos/containers/podman/releases/latest)
          LATEST_VERSION=$(echo "$LATEST_PODMAN_RELEASE" | jq -r '.tag_name' | sed 's/^v//')
          ASSETS=$(echo "$LATEST_PODMAN_RELEASE" | jq -r '.assets[].name' | tr '\n' ' ')
          echo $LATEST_VERSION
          echo $ASSETS
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_OUTPUT
          echo "$ASSETS" > assets.txt

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22
          package-manager-cache: false

      - name: Compare version numbers using npx semver
        id: compare_version_numbers
        run: |
          CURRENT_VERSION="${{ steps.get_current_version.outputs.CURRENT_VERSION }}"
          LATEST_VERSION="${{ steps.fetch_latest_podman_release.outputs.LATEST_VERSION }}"

          echo "Current version: $CURRENT_VERSION"
          echo "Latest version: $LATEST_VERSION"

          if npx semver "$LATEST_VERSION" -r ">$CURRENT_VERSION"; then
            echo "New version available: $LATEST_VERSION"
          else
            echo "No new version available."
            exit 0
          fi

      - name: Check for required assets in Podman release
        id: check_assets
        run: |
          REQUIRED_ASSETS=("podman-installer-windows-amd64.exe" "podman-installer-windows-arm64.exe" "podman-installer-macos-amd64.pkg" "podman-installer-macos-arm64.pkg" "podman-installer-macos-universal.pkg")
          MISSING_ASSETS=()
          echo "Assets found in release:"
          cat assets.txt

          for ASSET in "${REQUIRED_ASSETS[@]}"; do
            if ! grep -q "$ASSET" assets.txt; then
              MISSING_ASSETS+=("$ASSET")
            fi
          done

          if [ ${#MISSING_ASSETS[@]} -ne 0 ]; then
            echo "Error: Missing assets:"
            for asset in "${MISSING_ASSETS[@]}"; do
              echo "  - $asset"
            done
            exit 1
          else
            echo "All required assets are present."
          fi
